### PR TITLE
fix: Fatal session read error

### LINKED ISSUE #403: Fatal session read error
```
2025-07-03 17:00:49,608 [main] WARN  SessionManager.readSessionInfoFromZip:196 - Error reading manifest.json from bbc540d8-1515-49ae-8b25-fc3660bd66d5.zip: Cannot deserialize value of type `long` from Boolean value (token `JsonToken.VALUE_TRUE`)
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 123] (through reference chain: io.github.jbellis.brokk.SessionManager$SessionInfo["modified"])
```

### PR DESCRIPTION
**Pull request by bdragan**
Closes #403.

### CODE REVIEW

File: src/main/java/io/github/jbellis/brokk/SessionManager.java [hunk 1]
```diff
@@ -35,8 +35,9 @@ public class SessionManager implements AutoCloseable
      * Record representing session metadata for the sessions management system.
      */
     public record SessionInfo(UUID id, String name, long created, long modified) {
-
-        public boolean isModified() {
+        
+        @JsonIgnore
+        public boolean isSessionModified() {
             return created != modified;
         }
```
Comment (bdragan) [inline src/main/java/io/github/jbellis/brokk/SessionManager.java:42]: The method was unhappily named (so json property name was equal to the record property), plus I forgot `@JsonIgnore`.

File: src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java [hunk 2]
```diff
@@ -560,27 +561,36 @@ void testSaveAndLoadSessionHistory() throws Exception {
...
-        
+
+        // --- Verification with live session manager (cached sessions) ---
+        verifySessionHistory(sessionManager, sessionId, initialModifiedTime, originalHistory, "after save (cached sessions)");
+        project.close();
+
+        // --- Verification with new session manager (sessions loaded from disk) ---
+        MainProject newProject = new MainProject(tempDir);
+        verifySessionHistory(newProject.getSessionManager(), sessionId, initialModifiedTime, originalHistory, "after recreating project (sessions loaded from disk)");
+        newProject.close();
```
Comment (bdragan) [inline src/test/java/io/github/jbellis/brokk/context/ContextSerializationTest.java:572]: Extended the test case now to also reload and verify all session data from disk from a new project, because  everything worked fine before from cached session info.
