### PR TITLE
fix: NPE on data retention policy

### LINKED ISSUE #167: NPE on data retention policy
Related to #141 I'm seeing this when opening a new project and choosing a different Data retention policy

[error] Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "parentDialog" because "this.parentProjectPanel" is null
[error] 	at io.github.jbellis.brokk.gui.dialogs.SettingsProjectPanel$DataRetentionPanel.applyPolicy(SettingsProjectPanel.java:679)
[error] 	at io.github.jbellis.brokk.gui.dialogs.SettingsDialog.lambda$showStandaloneDataRetentionDialog$3(SettingsDialog.java:271)
[error] 	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
[error] 	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
[error] 	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
[error] 	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
[error] 	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
[error] 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)

### PR DESCRIPTION
**Pull request by bdragan**
Closes #167.

### CODE REVIEW

File: src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsDialog.java [hunk 1]
```diff
@@ -238,7 +238,7 @@ public static boolean showStandaloneDataRetentionDialog(IProject project, Frame
 
         var dialog = new JDialog(owner, "Data Retention Policy Required", true);
         dialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
-        dialog.setSize(600, 300); // Adjusted size
+        dialog.setSize(600, 350); // Adjusted size
```
Comment (bdragan) [inline src/main/java/io/github/jbellis/brokk/gui/dialogs/SettingsDialog.java:241]: On my machine, not all the content was shown with 300 height, so increased a bit:
image

Trying to solve with `dialog.pack()` made the dialog too wide because it seems pack() tends to keep labels (with html content in this case) on one line only.
