### PR TITLE
fix: Improve error messages for very short TTS

### LINKED ISSUE #866: Improve error messages for very short TTS
This from QuickEdit

Image

### PR DESCRIPTION
**Pull request by bdragan**
Closes #866:
image

### CODE REVIEW

File: app/src/main/java/io/github/jbellis/brokk/gui/VoiceInputButton.java [hunk 1]
```diff
@@ -271,15 +271,20 @@ private void stopMicCaptureAndTranscribe() {
 
         // Convert the in-memory raw PCM data to a valid .wav file
         var audioBytes = micBuffer.toByteArray();
+        var format = new AudioFormat(16000.0f, 16, 1, true, true);
+
+        // Pre-flight check for audio duration to avoid unnecessary API calls for very short clips
+        if (audioBytes.length / (format.getFrameRate() * format.getFrameSize()) < 0.5f) {
```
Comment (bdragan) [inline app/src/main/java/io/github/jbellis/brokk/gui/VoiceInputButton.java:277]: I think 0.5 seconds minimum should be more than fine.

**Review by jbellis — APPROVED** [review]
lgtm but pls use the new showNotification instead of toolError
