### PR TITLE
fix: [Bug]: initializing git repo when opening a project does not result in a GitRepo reference in the Project

### LINKED ISSUE #1068: [Bug]: initializing git repo when opening a project does not result in a GitRepo reference in the Project
### Brokk Version

master

### Operating System

macOS

### What happened?

```
java.lang.ClassCastException: class io.github.jbellis.brokk.git.LocalFileRepo cannot be cast to class io.github.jbellis.brokk.git.GitRepo (io.github.jbellis.brokk.git.LocalFileRepo and io.github.jbellis.brokk.git.GitRepo are in unnamed module of loader 'app')
	at io.github.jbellis.brokk.AnalyzerUtil.combinedRankingFor(AnalyzerUtil.java:55) ~[main/:?]
	at io.github.jbellis.brokk.context.Context.buildAutoContextFragment(Context.java:341) ~[main/:?]
	at io.github.jbellis.brokk.context.Context.buildAutoContext(Context.java:328) ~[main/:?]
	at io.github.jbellis.brokk.agents.ArchitectAgent.buildPrompt(ArchitectAgent.java:1026) ~[main/:?]
	at io.github.jbellis.brokk.agents.ArchitectAgent.execute(ArchitectAgent.java:646) ~[main/:?]
	at io.github.jbellis.brokk.gui.InstructionsPanel.executeArchitectCommand(InstructionsPanel.java:1692) ~[main/:?]
	at io.github.jbellis.brokk.gui.InstructionsPanel.lambda$runArchitectCommand$56(InstructionsPanel.java:1878) ~[main/:?]
	at io.github.jbellis.brokk.gui.InstructionsPanel.lambda$submitAction$60(InstructionsPanel.java:2052) ~[main/:?]
	at io.github.jbellis.brokk.ContextManager.lambda$submitUserTask$11(ContextManager.java:651) ~[main/:?]
	at io.github.jbellis.brokk.util.LoggingExecutorService.lambda$wrap$7(LoggingExecutorService.java:113) ~[main/:?]
	at io.github.jbellis.brokk.util.LoggingExecutorService.lambda$submit$2(LoggingExecutorService.java:58) ~[main/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1583) [?:?]
```

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by bdragan**
Closes #1068.

### CODE REVIEW

File: app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java [hunk 1]
```diff
@@ -2163,9 +2163,11 @@ public void close() {
      */
     public static void initRepo(Path root) throws GitAPIException, IOException {
         logger.info("Initializing new Git repository at {}", root);
-        Git.init().setDirectory(root.toFile()).call();
-        logger.info("Git repository initialized at {}.", root);
-        ensureBrokkIgnored(root);
+        try (var git = Git.init().setDirectory(root.toFile()).call()) {
+            logger.info("Git repository initialized at {}.", root);
+            ensureBrokkIgnored(root);
+            git.commit().setAllowEmpty(true).setMessage("Initial commit").call();
```
Comment (bdragan) [inline app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java:2169]: We require at least [one branch](https://github.com/BrokkAi/brokk/blob/432ff88a7d72f78e55e055ce62da3ac42106a08d/app/src/main/java/io/github/jbellis/brokk/git/GitRepo.java#L76) to exist in the repo.
